### PR TITLE
PostgreSQL function integration with psql pkg

### PR DESCRIPTION
**Pull request by aylapear**
- should `sbf_save_pg()` be changed to `sbf_copy_pg()`? 
    - This function does the dump, ie copies the entire database from the hosted server to a text file that can be saved

### CODE REVIEW

**Comment by aylapear** [comment]
This pull request adds the "core" Postgres functions:

- `sbf_open_pg()`
- `sbf_close_pg()`
- `sbf_save_pg()` (see comment above for name question)
- `sbf_create_pg()`
- `sbf_execute_pg()`
- `sbf_list_tables_pg()`
- `sbf_save_data_to_pg()`
- `sbf_load_data_to_pg()`
- `sbf_load_datas_to_pg()`



Then the parameter setting functions:

- `sbf_set_schema()`
- `sbf_get_schema()`
- `sbf_reset_schema()`

- `sbf_set_config_file()`
- `sbf_get_config_file()`
- `sbf_reset_config_file()`

- `sbf_set_config_value()`
- `sbf_get_config_value()`
- `sbf_reset_config_value()`

**Comment by aylapear** [comment]
The coverage action is failing, I am not entirely sure why it is failing. Based on the error message I am curious if it has to do with a permission issue as we have two since the error message coming out of the action has private in the folder path and the psql package is currently private. 

I am able to run the coverage locally and it passes but when I run `covr::codecov()` it has a connection error.

**Comment by aylapear** [comment]
R-CMD-check for lasted macOS version is failing while other 4 systems pass. The failure is due to sf not being properly installed. Not sure exact cause of this issue but not due to current new of new code.

**Comment by aylapear** [comment]
Fixed Mac-os sf download issue, it is caused by sf needing to be installed through its binaries at the moment. Linux can't install binaries so split code so linux installs from source and not linux (Mac and windows) install binary. Action is now passing for all operating systems.

**Comment by aylapear** [comment]
Coverage issue finally fixed, combination of private repo token issue and the lack of sf being properly downloaded. Changed how sf is downloaded by allowing binaries to be downloaded. Also made psql public so token is not required any more.

**Comment by aylapear** [comment]
- renamed `sbf_save_pg()` to `sbf_copy_pg()` to be more consistent with pkg naming

**Comment by aylapear** [comment]
- switched all the tests over to the tear down functions
- added test helper file for pg functions
- made tests more readable and reproducible

**Review by joethorley — APPROVED** [review]
looking good

**Pull request merged**
